# Generated by Django 2.2.1 on 2019-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('chegada', models.DateTimeField(auto_now_add=True)),
                ('duracao', models.IntegerField()),
                ('tempo_espera', models.IntegerField(default=0.0)),
            ],
            options={
                'db_table': 'Lista de Pronto',
                'ordering': ['duracao', 'chegada'],
            },
        ),
    ]
