# Generated by Django 2.2.1 on 2019-06-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalonador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['tamanho', 'chegada']},
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='duracao',
            new_name='tamanho',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tempo_espera',
        ),
    ]
